---
stages:
  - Build image
  - Build binaries

docker build:
  image: docker:18.09.5
  services:
    - docker:18.09.5-dind
  stage: Build image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG build/ci/
    - docker push $IMAGE_TAG
  only:
    changes:
      - build/ci/Dockerfile

build:
  image: golang:1.13.4-buster
  stage: Build binaries
  script:
    - apt update
    - apt install -y xorg-dev libglu1-mesa-dev
    - go mod download
    - go build -v ./cmd/fractalexplorer
  artifacts:
    paths:
      - fractalexplorer
